/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/behemoth_from_horizon_zero_dawn.glb -o src/components/three/BehemothModel.tsx -t --root public/ 
Author: Théo Domon (https://sketchfab.com/Gloomeskk)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/behemoth-from-horizon-zero-dawn-ff683e73f3ef4acb8546e643cd1d070a
Title: Behemoth from Horizon Zero Dawn
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder012_0: THREE.Mesh
    Cylinder012_0_1: THREE.Mesh
    Cylinder_0: THREE.Mesh
    Cylinder_0_1: THREE.Mesh
    Cylinder_0_2: THREE.Mesh
    Cylinder_0_3: THREE.Mesh
    Cylinder_0_4: THREE.Mesh
    Cylinder_0_5: THREE.Mesh
    Cylinder001_0: THREE.Mesh
    Cylinder004_0: THREE.Mesh
    Cube_0: THREE.Mesh
    Cube_0_1: THREE.Mesh
    Cube_0_2: THREE.Mesh
    Cube_0_3: THREE.Mesh
    Cube_0_4: THREE.Mesh
    Cylinder010_0: THREE.Mesh
    Cylinder011_0: THREE.Mesh
    Cylinder011_1: THREE.Mesh
    Cylinder025_0: THREE.Mesh
    Cylinder025_0_1: THREE.Mesh
    Cylinder009_0: THREE.Mesh
    Cylinder009_1: THREE.Mesh
    Cylinder033_0: THREE.Mesh
    Cylinder033_0_1: THREE.Mesh
    Cylinder034_0: THREE.Mesh
    Cylinder034_0_1: THREE.Mesh
    Cylinder035_0: THREE.Mesh
    Cylinder013_0: THREE.Mesh
    Cylinder036_0: THREE.Mesh
    Cylinder037_0: THREE.Mesh
    Cylinder038_0: THREE.Mesh
    Cylinder002_0: THREE.Mesh
    Cylinder003_0: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    Cylinder005_0: THREE.Mesh
    Cylinder005_1: THREE.Mesh
    Cylinder006_0: THREE.Mesh
    Cylinder006_1: THREE.Mesh
    Cylinder026_0: THREE.Mesh
    Cylinder026_1: THREE.Mesh
    Cylinder027_0: THREE.Mesh
    Cylinder027_1: THREE.Mesh
    Cylinder028_0: THREE.Mesh
    Cylinder028_1: THREE.Mesh
    Cylinder039_0: THREE.Mesh
    Cylinder039_1: THREE.Mesh
  }
  materials: {
    FRONT_LEG: THREE.MeshStandardMaterial
    BODY: THREE.MeshStandardMaterial
    DRUM: THREE.MeshStandardMaterial
    GRAVITY: THREE.MeshStandardMaterial
    material_8: THREE.MeshStandardMaterial
    FREEZE_CANISTER: THREE.MeshStandardMaterial
    BATTERY: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    REAR_LEG: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/behemoth_from_horizon_zero_dawn.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const actionName = Object.keys(actions)[0]
    if (actionName && actions[actionName]) {
      actions[actionName]?.play()
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, -0.472, 0]}>
          <mesh geometry={nodes.Cylinder012_0.geometry} material={materials.FRONT_LEG} />
          <mesh geometry={nodes.Cylinder012_0_1.geometry} material={materials.FRONT_LEG} />
        </group>
        <group position={[0, -0.491, 0]}>
          <mesh geometry={nodes.Cylinder025_0.geometry} material={materials.REAR_LEG} />
          <mesh geometry={nodes.Cylinder025_0_1.geometry} material={materials.REAR_LEG} />
        </group>
        <group position={[0.689, 2.698, -0.701]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cylinder009_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cylinder009_1.geometry} material={materials['Material.001']} />
        </group>
        <group position={[0, -0.472, 0]}>
          <mesh geometry={nodes.Cylinder033_0.geometry} material={materials.FRONT_LEG} />
          <mesh geometry={nodes.Cylinder033_0_1.geometry} material={materials.FRONT_LEG} />
        </group>
        <group position={[0, -0.491, 0]}>
          <mesh geometry={nodes.Cylinder034_0.geometry} material={materials.REAR_LEG} />
          <mesh geometry={nodes.Cylinder034_0_1.geometry} material={materials.REAR_LEG} />
        </group>
        <group position={[0.689, 2.798, -0.861]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cylinder003_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.001']} />
        </group>
        <group position={[0.613, 2.798, -0.946]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cylinder005_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Material.001']} />
        </group>
        <group position={[0.613, 2.698, -0.787]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cylinder006_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cylinder006_1.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-0.462, 2.698, -0.787]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cylinder026_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cylinder026_1.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-0.462, 2.798, -0.946]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cylinder027_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cylinder027_1.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-0.537, 2.798, -0.861]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cylinder028_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cylinder028_1.geometry} material={materials['Material.001']} />
        </group>
        <group position={[-0.537, 2.698, -0.701]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Cylinder039_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cylinder039_1.geometry} material={materials['Material.001']} />
        </group>
        <mesh geometry={nodes.Cylinder_0.geometry} material={materials.BODY} />
        <mesh geometry={nodes.Cylinder_0_1.geometry} material={materials.BODY} />
        <mesh geometry={nodes.Cylinder_0_2.geometry} material={materials.BODY} />
        <mesh geometry={nodes.Cylinder_0_3.geometry} material={materials.BODY} />
        <mesh geometry={nodes.Cylinder_0_4.geometry} material={materials.BODY} />
        <mesh geometry={nodes.Cylinder_0_5.geometry} material={materials.BODY} />
        <mesh geometry={nodes.Cylinder001_0.geometry} material={materials.DRUM} position={[0, -2.028, 0]} rotation={[0, 0, -Math.PI]} />
        <mesh geometry={nodes.Cylinder004_0.geometry} material={materials.GRAVITY} />
        <mesh geometry={nodes.Cube_0.geometry} material={materials.material_8} />
        <mesh geometry={nodes.Cube_0_1.geometry} material={materials.material_8} />
        <mesh geometry={nodes.Cube_0_2.geometry} material={materials.material_8} />
        <mesh geometry={nodes.Cube_0_3.geometry} material={materials.material_8} />
        <mesh geometry={nodes.Cube_0_4.geometry} material={materials.material_8} />
        <mesh geometry={nodes.Cylinder010_0.geometry} material={materials.FREEZE_CANISTER} />
        <mesh geometry={nodes.Cylinder011_0.geometry} material={materials.BATTERY} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder035_0.geometry} material={materials.GRAVITY} />
        <mesh geometry={nodes.Cylinder013_0.geometry} material={materials.GRAVITY} position={[-0.126, -0.564, 0.761]} />
        <mesh geometry={nodes.Cylinder036_0.geometry} material={materials.GRAVITY} position={[0.128, -0.564, 0.761]} />
        <mesh geometry={nodes.Cylinder037_0.geometry} material={materials.GRAVITY} position={[-0.126, -1.311, 1.346]} />
        <mesh geometry={nodes.Cylinder038_0.geometry} material={materials.GRAVITY} position={[0.123, -1.311, 1.346]} />
        <mesh geometry={nodes.Cylinder002_0.geometry} material={materials.FREEZE_CANISTER} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/behemoth_from_horizon_zero_dawn.glb')
