/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/eye_robot.glb -o src/components/three/EyeRobotModel.tsx -t --root public/ 
Author: typhomnt (https://sketchfab.com/typhomnt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eye-robot-0f62aedb1f564133b259b1dd02297673
Title: Eye Robot
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
  }
  materials: {
    Body: THREE.MeshStandardMaterial
    Canon: THREE.MeshStandardMaterial
    Engine: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    EyeGlass: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/eye_robot.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Canon} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Engine} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.EyeGlass} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/eye_robot.glb')
