/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/humanoid_robot_ai.glb -o src/components/three/HumanoidRobotAI.tsx -t --root public/ 
Author: 3dUVpro (https://sketchfab.com/3dUVpro)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/humanoid-robot-ai-e5de866d076646be8f20c610fefbbbcf
Title: Humanoid robot Ai
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL + 'models/humanoid_robot_ai.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'models/humanoid_robot_ai.glb')
