/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/modular_mecha_doll_neon_mask.glb -t -o src/components/three/MechaDollModel.tsx 
Author: ChamberSu1996 (https://sketchfab.com/chambersu1996)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modular-mecha-doll-neon-mask-1e0dcf3e016f4bc897d4b39819220732
Title: Modular Mecha Doll Neon Mask
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props: React.ComponentProps<'group'>) {
  const { scene } = useGLTF(import.meta.env.BASE_URL + 'models/modular_mecha_doll_neon_mask.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={scene} />
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'models/modular_mecha_doll_neon_mask.glb')
