/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/sci_fi_head_low_poly.glb -o src/components/three/RobotHeadModel.tsx -t --root public/ 
Author: Payam Tavakoli (https://sketchfab.com/payamtavakoli)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-head-low-poly-e472fa3f74cf4ccf9266687b376c1789
Title: Sci Fi Head Low Poly
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_3: THREE.Mesh
  }
  materials: {
    Default: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL + 'models/sci_fi_head_low_poly.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.Default} position={[-74.763, -53.796, -17.541]} />
      </group>
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'models/sci_fi_head_low_poly.glb')
