/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/robot_a04.glb -o src/components/three/RobotA04Model.tsx -t --root public/ 
Author: Lukas Hahn Graphics (https://sketchfab.com/specter)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-a04-c090642fcc334639a6a03ab8f6b0e446
Title: Robot A04
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Chest_inner_Metal_Dirty_1: THREE.Mesh
    Sweep_3_Mat2_0: THREE.Mesh
    Sweep_4_Mat2_0: THREE.Mesh
    Sweep_5_Mat2_0: THREE.Mesh
    Sweep_2_Mat2_0: THREE.Mesh
    Sweep_1_Mat2_0: THREE.Mesh
    Chest_Metal_Dirty1_1: THREE.Mesh
    eye_mid__1: THREE.Mesh
    eye_mid_Mat1_1: THREE.Mesh
    eyes__1: THREE.Mesh
    eyes_Mat1_1: THREE.Mesh
    Head_1_Metal_Dirty2_1: THREE.Mesh
    Spine_Metal_Dirty3_1: THREE.Mesh
    Sweep_2_2_Mat2_0: THREE.Mesh
    Sweep_1_2_Mat2_0: THREE.Mesh
    lower_arm_Metal_Dirty9_0: THREE.Mesh
    Sweep_2_3_Mat2_0: THREE.Mesh
    Sweep_1_3_Mat2_0: THREE.Mesh
    ['W��rfel_2_Metal_Dirty15_0']: THREE.Mesh
    ['W��rfel_1_Metal_Dirty13_0']: THREE.Mesh
    Finger_P_Metal_Dirty11_0: THREE.Mesh
    ['W��rfel_2_2_Metal_Dirty21_0']: THREE.Mesh
    ['W��rfel_1_2_Metal_Dirty19_0']: THREE.Mesh
    Finger_R_Metal_Dirty17_0: THREE.Mesh
    ['W��rfel_2_3_Metal_Dirty27_0']: THREE.Mesh
    ['W��rfel_1_3_Metal_Dirty25_0']: THREE.Mesh
    ['W��rfel_3_Metal_Dirty23_0']: THREE.Mesh
    ['W��rfel_2_4_Metal_Dirty33_0']: THREE.Mesh
    ['W��rfel_1_4_Metal_Dirty31_0']: THREE.Mesh
    Finger_M_Metal_Dirty29_0: THREE.Mesh
    Hand_base_Metal_Dirty35_0: THREE.Mesh
    Elbow_Metal_Dirty7_0: THREE.Mesh
    Arm_Metal_Dirty5_0: THREE.Mesh
    Shoulder_Metal_Dirty4_1: THREE.Mesh
    Foot__Metal_Dirty40_0: THREE.Mesh
    Leg_down_Metal_Dirty38_0: THREE.Mesh
    Knee_Metal_Dirty37_1: THREE.Mesh
    Knee_2_Metal_Dirty42_1: THREE.Mesh
    Sweep_2_4_Mat2_0: THREE.Mesh
    Sweep_1_4_Mat2_0: THREE.Mesh
    ['W��rfel_3_2_Metal_Dirty43_1']: THREE.Mesh
    Pelvis_Metal_Dirty44_1: THREE.Mesh
  }
  materials: {
    Metal_Dirty: THREE.MeshStandardMaterial
    ['Mat.2']: THREE.MeshStandardMaterial
    ['Mat.2_0']: THREE.MeshStandardMaterial
    ['Metal_Dirty.1']: THREE.MeshStandardMaterial
    RootNode: THREE.MeshStandardMaterial
    ['Mat.1']: THREE.MeshStandardMaterial
    ['Metal_Dirty.2']: THREE.MeshStandardMaterial
    ['Metal_Dirty.3']: THREE.MeshStandardMaterial
    ['Metal_Dirty.9']: THREE.MeshStandardMaterial
    ['Metal_Dirty.15']: THREE.MeshStandardMaterial
    ['Metal_Dirty.13']: THREE.MeshStandardMaterial
    ['Metal_Dirty.11']: THREE.MeshStandardMaterial
    ['Metal_Dirty.21']: THREE.MeshStandardMaterial
    ['Metal_Dirty.19']: THREE.MeshStandardMaterial
    ['Metal_Dirty.17']: THREE.MeshStandardMaterial
    ['Metal_Dirty.27']: THREE.MeshStandardMaterial
    ['Metal_Dirty.25']: THREE.MeshStandardMaterial
    ['Metal_Dirty.23']: THREE.MeshStandardMaterial
    ['Metal_Dirty.33']: THREE.MeshStandardMaterial
    ['Metal_Dirty.31']: THREE.MeshStandardMaterial
    ['Metal_Dirty.29']: THREE.MeshStandardMaterial
    ['Metal_Dirty.35']: THREE.MeshStandardMaterial
    ['Metal_Dirty.7']: THREE.MeshStandardMaterial
    ['Metal_Dirty.5']: THREE.MeshStandardMaterial
    ['Metal_Dirty.4']: THREE.MeshStandardMaterial
    ['Metal_Dirty.40']: THREE.MeshStandardMaterial
    ['Metal_Dirty.38']: THREE.MeshStandardMaterial
    ['Metal_Dirty.37']: THREE.MeshStandardMaterial
    ['Metal_Dirty.42']: THREE.MeshStandardMaterial
    ['Metal_Dirty.43']: THREE.MeshStandardMaterial
    ['Metal_Dirty.44']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL + 'models/robot_a04.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.006, 0.529]} rotation={[-1.57, 0, 0]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -38.359, 0.609]}>
            <group position={[0, 99.982, 184.668]} rotation={[1.667, 0, 0]}>
              <mesh geometry={nodes.eye_mid__1.geometry} material={materials.RootNode} />
              <mesh geometry={nodes.eye_mid_Mat1_1.geometry} material={materials['Mat.1']} />
            </group>
            <group position={[108.399, 41.491, 123.789]} rotation={[1.667, Math.PI / 2, 0]}>
              <mesh geometry={nodes.eyes__1.geometry} material={materials.RootNode} />
              <mesh geometry={nodes.eyes_Mat1_1.geometry} material={materials['Mat.1']} />
            </group>
            <group position={[0, -337.792, -0.609]}>
              <group position={[419.246, 23.833, -169.411]}>
                <group position={[98.752, 4.06, 5.247]}>
                  <group position={[200.594, -831.274, -51.212]} rotation={[0.769, 0.256, -0.24]}>
                    <group position={[-96.596, -165.876, 435.079]} rotation={[0.073, -0.125, 1.976]} scale={[-1, 1, 1]}>
                      <group position={[-8.113, 0.735, 307.651]}>
                        <group position={[-57.483, -2.224, -68.299]} rotation={[0, -0.175, 0]} scale={[-1, 1, 1]}>
                          <group position={[0, 0, 93.89]} rotation={[-0.617, 0, 0]}>
                            <mesh geometry={nodes['W��rfel_1_Metal_Dirty13_0'].geometry} material={materials['Metal_Dirty.13']} />
                            <mesh geometry={nodes['W��rfel_2_Metal_Dirty15_0'].geometry} material={materials['Metal_Dirty.15']} position={[0, 0, 94.58]} rotation={[-Math.PI / 6, 0, 0]} />
                          </group>
                          <mesh geometry={nodes.Finger_P_Metal_Dirty11_0.geometry} material={materials['Metal_Dirty.11']} />
                        </group>
                        <group position={[64.472, -2.224, -68.299]} rotation={[-0.089, 0.174, 0.015]} scale={[-1, 1, 1]}>
                          <group position={[0, 0, 93.89]} rotation={[-0.746, 0, 0]}>
                            <mesh geometry={nodes['W��rfel_1_2_Metal_Dirty19_0'].geometry} material={materials['Metal_Dirty.19']} />
                            <mesh geometry={nodes['W��rfel_2_2_Metal_Dirty21_0'].geometry} material={materials['Metal_Dirty.21']} position={[0, 0, 94.58]} rotation={[-0.922, 0, 0]} />
                          </group>
                          <mesh geometry={nodes.Finger_R_Metal_Dirty17_0.geometry} material={materials['Metal_Dirty.17']} />
                        </group>
                        <group position={[-109.849, -4.159, -96.221]} rotation={[-0.782, -0.702, -0.57]} scale={[-1, 1, 1]}>
                          <group position={[0, 0, 63.589]} rotation={[-0.26, -0.503, 0]}>
                            <mesh geometry={nodes['W��rfel_1_3_Metal_Dirty25_0'].geometry} material={materials['Metal_Dirty.25']} />
                            <mesh geometry={nodes['W��rfel_2_3_Metal_Dirty27_0'].geometry} material={materials['Metal_Dirty.27']} position={[0, 0, 56.025]} rotation={[-0.509, 0, 0]} />
                          </group>
                          <mesh geometry={nodes['W��rfel_3_Metal_Dirty23_0'].geometry} material={materials['Metal_Dirty.23']} />
                        </group>
                        <group position={[3.229, -2.224, -68.299]} scale={[-1, 1, 1]}>
                          <group position={[0, 0, 103.837]} rotation={[-Math.PI / 6, 0, 0]}>
                            <mesh geometry={nodes['W��rfel_1_4_Metal_Dirty31_0'].geometry} material={materials['Metal_Dirty.31']} />
                            <mesh geometry={nodes['W��rfel_2_4_Metal_Dirty33_0'].geometry} material={materials['Metal_Dirty.33']} position={[0, 0, 104.601]} rotation={[-Math.PI / 6, 0, 0]} />
                          </group>
                          <mesh geometry={nodes.Finger_M_Metal_Dirty29_0.geometry} material={materials['Metal_Dirty.29']} />
                        </group>
                      </group>
                      <mesh geometry={nodes.Sweep_2_3_Mat2_0.geometry} material={materials['Mat.2_0']} position={[-1161.729, 386.829, -1238.69]} rotation={[0.045, -0.815, 1.793]} scale={[-1, 1, 1]} />
                      <mesh geometry={nodes.Sweep_1_3_Mat2_0.geometry} material={materials['Mat.2']} position={[-1161.729, 386.829, -1238.69]} rotation={[0.045, -0.815, 1.793]} scale={[-1, 1, 1]} />
                      <mesh geometry={nodes.Hand_base_Metal_Dirty35_0.geometry} material={materials['Metal_Dirty.35']} position={[-8.432, 63.026, 68.577]} />
                    </group>
                    <mesh geometry={nodes.Elbow_Metal_Dirty7_0.geometry} material={materials['Metal_Dirty.7']} />
                    <mesh geometry={nodes.lower_arm_Metal_Dirty9_0.geometry} material={materials['Metal_Dirty.9']} position={[-2.524, -0.816, 39.1]} rotation={[0, -0.239, 0]} />
                  </group>
                  <mesh geometry={nodes.Arm_Metal_Dirty5_0.geometry} material={materials['Metal_Dirty.5']} />
                  <mesh geometry={nodes.Sweep_2_2_Mat2_0.geometry} material={materials['Mat.2']} position={[-517.997, 348.258, 164.164]} />
                  <mesh geometry={nodes.Sweep_1_2_Mat2_0.geometry} material={materials['Mat.2_0']} position={[-517.997, 348.258, 164.164]} />
                </group>
                <mesh geometry={nodes.Shoulder_Metal_Dirty4_1.geometry} material={materials['Metal_Dirty.4']} />
              </group>
            </group>
            <group position={[0, 38.359, -0.609]}>
              <group position={[311.36, -2177.277, 82.437]}>
                <group position={[-311.36, 2062.184, -82.437]}>
                  <group position={[311.36, -2177.277, 82.437]} rotation={[0, 0.244, 0]}>
                    <mesh geometry={nodes.Leg_down_Metal_Dirty38_0.geometry} material={materials['Metal_Dirty.38']} />
                    <mesh geometry={nodes.Foot__Metal_Dirty40_0.geometry} material={materials['Metal_Dirty.40']} position={[20.526, -1073.929, -9.523]} />
                  </group>
                </group>
                <mesh geometry={nodes.Knee_Metal_Dirty37_1.geometry} material={materials['Metal_Dirty.37']} />
              </group>
            </group>
            <group position={[0, 38.359, -0.609]}>
              <mesh geometry={nodes.Knee_2_Metal_Dirty42_1.geometry} material={materials['Metal_Dirty.42']} position={[311.36, -2177.277, 82.437]} />
            </group>
            <group position={[0, 38.359, -0.609]}>
              <group position={[313.811, -1434.961, -128.936]}>
                <mesh geometry={nodes['W��rfel_3_2_Metal_Dirty43_1'].geometry} material={materials['Metal_Dirty.43']} />
                <mesh geometry={nodes.Sweep_2_4_Mat2_0.geometry} material={materials['Mat.2_0']} position={[-313.811, 1434.961, 128.936]} />
                <mesh geometry={nodes.Sweep_1_4_Mat2_0.geometry} material={materials['Mat.2']} position={[-313.811, 1434.961, 128.936]} />
              </group>
            </group>
            <mesh geometry={nodes.Chest_inner_Metal_Dirty_1.geometry} material={materials.Metal_Dirty} position={[0, -558.246, -11.744]} rotation={[-0.288, 0, Math.PI]} />
            <mesh geometry={nodes.Sweep_3_Mat2_0.geometry} material={materials['Mat.2']} position={[0, 631.18, -0.609]} />
            <mesh geometry={nodes.Sweep_4_Mat2_0.geometry} material={materials['Mat.2']} position={[0, 631.18, -0.609]} />
            <mesh geometry={nodes.Sweep_5_Mat2_0.geometry} material={materials['Mat.2_0']} position={[0, 631.18, -0.609]} />
            <mesh geometry={nodes.Sweep_2_Mat2_0.geometry} material={materials['Mat.2']} position={[0, 38.359, -0.609]} />
            <mesh geometry={nodes.Sweep_1_Mat2_0.geometry} material={materials['Mat.2_0']} position={[0, 38.359, -0.609]} />
            <mesh geometry={nodes.Chest_Metal_Dirty1_1.geometry} material={materials['Metal_Dirty.1']} position={[160.1, -447.138, -0.609]} />
            <mesh geometry={nodes.Head_1_Metal_Dirty2_1.geometry} material={materials['Metal_Dirty.2']} position={[0, 5.93, 40.345]} rotation={[0.41, 0, 0]} />
            <mesh geometry={nodes.Spine_Metal_Dirty3_1.geometry} material={materials['Metal_Dirty.3']} position={[0, 38.359, -140.776]} />
            <mesh geometry={nodes.Pelvis_Metal_Dirty44_1.geometry} material={materials['Metal_Dirty.44']} position={[0, -1313.757, -0.609]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'models/robot_a04.glb')
