/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/6_axis_industrial_robot_arm.glb -o src/components/three/RobotArmModel.tsx -t --root public/ 
Author: Jayson Stauffer (https://sketchfab.com/JaysonStauffer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/6-axis-industrial-robot-arm-3ecc74c22c584b2b8295f17dedcdb89f
Title: 6 Axis Industrial Robot Arm
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    robolow_Hansrobottt2_svgBlinn1_0: THREE.Mesh
  }
  materials: {
    Hansrobottt2_svgBlinn1: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(import.meta.env.BASE_URL + 'models/6_axis_industrial_robot_arm.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.106}>
        <mesh geometry={nodes.robolow_Hansrobottt2_svgBlinn1_0.geometry} material={materials.Hansrobottt2_svgBlinn1} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload(import.meta.env.BASE_URL + 'models/6_axis_industrial_robot_arm.glb')
